-- CreateTable
CREATE TABLE "mainstock" (
    "kd_brgdg" TEXT NOT NULL,
    "nm_brgdg" TEXT NOT NULL,
    "id_dept" INTEGER NOT NULL,
    "isi" INTEGER NOT NULL,
    "id_satuan" INTEGER NOT NULL,
    "strip" INTEGER NOT NULL,
    "mark_up" DOUBLE PRECISION NOT NULL,
    "hb_netto" DOUBLE PRECISION NOT NULL,
    "hb_gross" DOUBLE PRECISION NOT NULL,
    "hj_ecer" DOUBLE PRECISION NOT NULL,
    "hj_bbs" DOUBLE PRECISION NOT NULL,
    "id_kategori" INTEGER NOT NULL,
    "id_pabrik" INTEGER NOT NULL,
    "barcode" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_status" BOOLEAN NOT NULL DEFAULT false,
    "deleted_at" TIMESTAMP(3),
    "hpp" DOUBLE PRECISION NOT NULL,
    "q_bbs" INTEGER NOT NULL,
    "sat_pus" INTEGER NOT NULL,
    "sat_cab" INTEGER NOT NULL,
    "tgl_new_product" TIMESTAMP(3) NOT NULL,
    "konsinyasi" BOOLEAN NOT NULL,
    "halodoc" BOOLEAN NOT NULL,
    "bpjs" BOOLEAN NOT NULL,
    "informasi_po" TEXT,
    "informasi_tanggal_ed_po" TIMESTAMP(3),
    "id_dept_pusdis" INTEGER NOT NULL,
    "trading_term" TEXT,
    "id_kl" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "moq" INTEGER NOT NULL,
    "min_bulan_ed" INTEGER NOT NULL,
    "informasi_return" TEXT,
    "barcode_big" TEXT,
    "hb_net" DOUBLE PRECISION NOT NULL,
    "mark_up_purchasing" DOUBLE PRECISION NOT NULL,
    "hna" DOUBLE PRECISION NOT NULL,
    "hj_masiva" DOUBLE PRECISION NOT NULL,
    "sup1" TEXT,
    "q_temp_out" INTEGER NOT NULL,
    "q_exp" INTEGER NOT NULL,
    "disc1" DOUBLE PRECISION NOT NULL,
    "q_akhir" INTEGER NOT NULL,
    "produksi" TEXT,
    "het" DOUBLE PRECISION NOT NULL,
    "berat" DOUBLE PRECISION NOT NULL,
    "nie" TEXT,
    "tgl_berlaku_nie" TIMESTAMP(3),
    "file_nie" TEXT,
    "updated_at" TIMESTAMP(3),
    "updated_by" TEXT,
    "id_brand" INTEGER NOT NULL,
    "wso2transfer" BOOLEAN NOT NULL,
    "is_updated" BOOLEAN NOT NULL,

    CONSTRAINT "mainstock_pkey" PRIMARY KEY ("kd_brgdg")
);
