APP_NAME: "user-rest-service"
HTTP_PORT: "3006"

DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/db_apotek"


API_AUTH_URL: "http://user-service-host:8081/api/user"

JWT_SECRET_KEY: "JWT_SECRET_KEY_APP_APOTEK_PBF))(**"
