FROM node:18-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy entire project
COPY . .

# Install dependencies
WORKDIR /app/apps/user-service
RUN npm install --verbose
RUN npm i nodemon -g

# Generate Prisma client
RUN npx prisma generate


CMD ["npm", "run", "dev"]

EXPOSE 3003