import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/QueryProvider";
import SetupKassaModal from "@/components/modals/SetupKassaModal";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Tambahkan searchParams agar bisa baca query parameter dari server
export default function RootLayout({
  children,
  searchParams,
}: Readonly<{
  children: React.ReactNode;
  searchParams: { modal?: string };
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
        <Toaster position="top-center" />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}