FROM node:18-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY ./frontend_v3/package.json ./frontend_v3/yarn.lock* ./frontend_v3/package-lock.json* ./frontend_v3/pnpm-lock.yaml* ./

RUN \
    if [ -f yarn.lock ]; then echo 'Installing with Yarn' && yarn install --frozen-lockfile --prefer-offline; \
    elif [ -f package-lock.json ]; then echo 'Installing with npm' && npm ci; \
    elif [ -f pnpm-lock.yaml ]; then echo 'Installing with pnpm' && npm i -g pnpm && pnpm i --frozen-lockfile; \
    else echo 'Lockfile not found. please ensure that either yarn.lock, package-lock.json or pnpm-lock.yaml is present.' && exit 1; \
    fi

COPY . .

CMD \
    if [ -f yarn.lock ]; then yarn dev; \
    elif [ -f package-lock.json ]; then npm run dev; \
    elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
    fi

EXPOSE 3000
