APP_NAME: "sales-rest-service"
HTTP_PORT: "3001"

DATABASE_URL: "postgresql://root:password@localhost:5433/db_sales?schema=public"


API_AUTH_URL: "http://auth-service-host:8081/api/auth"

JWT_SECRET_KEY: "JWT_SECRET_KEY_APP_APOTEK_PBF))(**"
