/*
  Warnings:

  - You are about to drop the `mainstock` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "mainstock";

-- CreateTable
CREATE TABLE "Mainstock" (
    "kd_brgdg" SERIAL NOT NULL,
    "nm_brgdg" TEXT NOT NULL,
    "id_dept" INTEGER NOT NULL,
    "isi" INTEGER NOT NULL,
    "id_satuan" INTEGER NOT NULL,
    "strip" INTEGER NOT NULL,
    "mark_up" DOUBLE PRECISION NOT NULL,
    "hb_netto" DOUBLE PRECISION NOT NULL,
    "hb_gross" DOUBLE PRECISION NOT NULL,
    "hj_ecer" DOUBLE PRECISION NOT NULL,
    "hj_bbs" DOUBLE PRECISION NOT NULL,
    "id_kategori" INTEGER NOT NULL,
    "id_pabrik" INTEGER NOT NULL,
    "barcode" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_status" BOOLEAN NOT NULL DEFAULT false,
    "deleted_at" TIMESTAMP(3),
    "hpp" DOUBLE PRECISION NOT NULL,
    "q_bbs" INTEGER NOT NULL,
    "sat_pus" INTEGER NOT NULL,
    "sat_cab" INTEGER NOT NULL,
    "tgl_new_product" TIMESTAMP(3) NOT NULL,
    "konsinyasi" BOOLEAN NOT NULL,
    "halodoc" BOOLEAN NOT NULL,
    "bpjs" BOOLEAN NOT NULL,
    "informasi_po" TEXT,
    "informasi_tanggal_ed_po" TIMESTAMP(3),
    "id_dept_pusdis" INTEGER NOT NULL,
    "trading_term" TEXT,
    "id_kl" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "moq" INTEGER NOT NULL,
    "min_bulan_ed" INTEGER NOT NULL,
    "informasi_return" TEXT,
    "barcode_big" TEXT,
    "hb_net" DOUBLE PRECISION NOT NULL,
    "mark_up_purchasing" DOUBLE PRECISION NOT NULL,
    "hna" DOUBLE PRECISION NOT NULL,
    "hj_masiva" DOUBLE PRECISION NOT NULL,
    "sup1" TEXT,
    "q_temp_out" INTEGER NOT NULL,
    "q_exp" INTEGER NOT NULL,
    "disc1" DOUBLE PRECISION NOT NULL,
    "q_akhir" INTEGER NOT NULL,
    "produksi" TEXT,
    "het" DOUBLE PRECISION NOT NULL,
    "berat" DOUBLE PRECISION NOT NULL,
    "nie" TEXT,
    "tgl_berlaku_nie" TIMESTAMP(3),
    "file_nie" TEXT,
    "updated_at" TIMESTAMP(3),
    "updated_by" TEXT,
    "id_brand" INTEGER NOT NULL,
    "wso2transfer" BOOLEAN NOT NULL,
    "is_updated" BOOLEAN NOT NULL,

    CONSTRAINT "Mainstock_pkey" PRIMARY KEY ("kd_brgdg")
);

-- CreateTable
CREATE TABLE "ReturPenjualan" (
    "id" SERIAL NOT NULL,
    "id_hretur" INTEGER NOT NULL,
    "detail" TEXT,
    "kd_brgdg" TEXT NOT NULL,
    "qty" INTEGER NOT NULL,
    "harga" DECIMAL(10,2) NOT NULL,
    "discount" DECIMAL(10,2) NOT NULL,
    "ppn" DECIMAL(10,2) NOT NULL,
    "subtotal_harga" DECIMAL(12,2) NOT NULL,
    "subtotal_discount" DECIMAL(12,2) NOT NULL,
    "subtotal_ppn" DECIMAL(12,2) NOT NULL,
    "no_batch" TEXT,
    "tgl_batch" TIMESTAMP(3),
    "id_hretur_cabang" INTEGER,
    "detail_retur_cabang" TEXT,
    "status_retur" TEXT,
    "nominal_retur" DECIMAL(12,2),
    "hpp" DECIMAL(10,2) NOT NULL,
    "total_hpp" DECIMAL(12,2) NOT NULL,
    "wso2transfer" BOOLEAN NOT NULL,
    "id_htransb" INTEGER NOT NULL,

    CONSTRAINT "ReturPenjualan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TransaksiPenjualan" (
    "id" SERIAL NOT NULL,
    "kd_brgdg" TEXT NOT NULL,
    "nm_brgdg" TEXT NOT NULL,
    "id_dept" INTEGER NOT NULL,
    "psn" INTEGER NOT NULL,
    "pisi" INTEGER NOT NULL,
    "ktr" TEXT,
    "sat_psn" INTEGER NOT NULL,
    "sld" INTEGER NOT NULL,
    "nilaipo" DECIMAL(12,2) NOT NULL,
    "trana" DECIMAL(12,2) NOT NULL,
    "tranb" DECIMAL(12,2) NOT NULL,
    "trana_r" DECIMAL(12,2),
    "tranb_r" DECIMAL(12,2),
    "q_akhir" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "tgl_input" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "hb_gross" DECIMAL(10,2) NOT NULL,
    "isi" INTEGER NOT NULL,
    "status" TEXT,
    "cito" BOOLEAN NOT NULL,
    "buffer" INTEGER NOT NULL,
    "sat_cab" INTEGER NOT NULL,
    "interval_transaksi" INTEGER NOT NULL,
    "rata_rata_qty_jual" DECIMAL(10,2),
    "katagori" TEXT,
    "tot_psn" INTEGER NOT NULL,
    "pesan" INTEGER NOT NULL,
    "psn_kalkulasi" INTEGER NOT NULL,
    "qty_po" INTEGER NOT NULL,
    "qty_beli" INTEGER NOT NULL,
    "qty_kurang" INTEGER NOT NULL,
    "jumlah_po" INTEGER NOT NULL,
    "nilai_max" DECIMAL(12,2) NOT NULL,
    "tranc" DECIMAL(12,2),
    "tranc_r" DECIMAL(12,2),
    "buffer_max" INTEGER,
    "tot_max" DECIMAL(12,2),
    "depo" TEXT,
    "q_bbs" INTEGER NOT NULL,
    "jml_trans" INTEGER NOT NULL,
    "jenis" TEXT,
    "trand" DECIMAL(12,2),
    "trand_r" DECIMAL(12,2),
    "sat_pus" INTEGER NOT NULL,
    "grade" TEXT,
    "t1" INTEGER,
    "t2" INTEGER,
    "hna" DECIMAL(10,2) NOT NULL,
    "min_max" INTEGER NOT NULL,
    "kd_cab" TEXT NOT NULL,
    "hpp" DECIMAL(10,2) NOT NULL,
    "infor" TEXT,

    CONSTRAINT "TransaksiPenjualan_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ReturPenjualan" ADD CONSTRAINT "ReturPenjualan_id_htransb_fkey" FOREIGN KEY ("id_htransb") REFERENCES "TransaksiPenjualan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
