apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-pembelian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service-pembelian
  template:
    metadata:
      labels:
        app: inventory-service-pembelian
    spec:
      containers:
      - name: inventory-service-pembelian
        image: your-registry/inventory-service-pembelian:latest
        ports:
        - containerPort: 3003
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL