FROM node:18-alpine

# Install OpenSSL and other dependencies
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Copy entire project
COPY . .

# Install dependencies
WORKDIR /app/apps/inventory-service-pembelian
RUN npm install --verbose

# Generate Prisma client with correct binary targets
RUN npx prisma generate --schema=./prisma/schema.prisma

# Build the application
RUN npm run build

CMD ["npm", "start"]

EXPOSE 3003