import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideNav from "@/components/SideNav";
import MarginWidthWrapper from "@/components/MarginWidthWrapper";
import Header from "@/components/Header";
import HeaderMobile from "@/components/HeaderMobile";
import PageWrapper from "@/components/PageWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-5">
            <SideNav />
            <MarginWidthWrapper>
                <Header />
                <HeaderMobile/>
                <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
        </main>
      </body>
    </html>
  );
}
