APP_NAME: "auth-service:-rest-service"
HTTP_PORT: "3007"

DATABASE_URL: "postgresql://root:password@postgres:5432/db_user?schema=public"


API_AUTH_URL: "http://auth-service-host:8081/api/auth"

JWT_SECRET_KEY: "JWT_SECRET_KEY_APP_APOTEK_PBF))(**"
