APP_NAME: "auth-service:-rest-service"
HTTP_PORT: "3007"

DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/db_apotek"


API_AUTH_URL: "http://auth-service-host:8081/api/auth"

JWT_SECRET_KEY: "JWT_SECRET_KEY_APP_APOTEK_PBF))(**"
