APP_NAME: "purchase-rest-service"
HTTP_PORT: "8084"

DB_DSN: "postgres://apps:obwMHF3sI%3C87@101.255.118.131:5703/db_pbf?sslmode=disable"
DB_MAX_IDLE_CONNECTIONS: "20"
DB_MAX_OPEN_CONNECTIONS: "100"
DB_MAX_IDLE_DURATION_IN_SECS: "60"
DB_MAX_LIFE_TIME_DURATION_IN_SECS: "300"

REDIS_HOST: "localhost"
REDIS_PORT: "6379"
REDIS_PASSWORD: ""
REDIS_MAX_IDLE: "10"

JWT_SECRET_KEY: "JWT_SECRET_KEY_APP_APOTEK_PBF))(**"

API_AUTH_URL: "https://demo-app.pegelinux.my.id/api/auth"
API_INVENTORY_URL: "https://demo-app.pegelinux.my.id/api/inventory"
API_USER_URL: "https://demo-app.pegelinux.my.id/api/user"
API_SUPPLIER_URL: "https://demo-app.pegelinux.my.id/api/supplier"