on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yaml'

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: |
          cd frontend
          if [ -f "yarn.lock" ]; then
            echo "Using Yarn"
            yarn install
          elif [ -f "package.json" ]; then
            echo "Using npm"
            npm ci
          else
            echo "Unable to determine package manager"
            exit 1
          fi