on:
  push:
    paths:
      - 'user-service/**'
      - '.github/workflows/user-service_ci.yaml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: build
        run: go build ./user-service/cmd

      - name: test
        run: go test ./user-service/...
